services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./marketplace_backend/.env
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network
  # db:
  #   image: mysql:latest
  #   ports:
  #     - '3306:3306'
  #   env_file:
  #     - ./marketplace_backend/.env
  #   restart: always
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - my_network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka_data:/bitnami/kafka 
    networks:
      - my_network

  marketplace_backend_gateway:
    build:
      context: ./marketplace_backend
      dockerfile: apps/marketplace_backend_gateway/Dockerfile
      target: development
    command: pnpm run start:dev marketplace_backend_gateway
    env_file:
      - ./marketplace_backend/apps/marketplace_backend_gateway/.env
    ports:
      - '3000:3000'
    volumes:
      - ./marketplace_backend:/app
    depends_on:
      - kafka    
      - db
    networks:
      - my_network
    environment:
      - KAFKA_BROKER=kafka:9092    
  auth:
    build:
      context: ./marketplace_backend
      dockerfile: apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./marketplace_backend/apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - ./marketplace_backend:/app
    depends_on:
      - kafka    
      - db
    networks:
      - my_network

  products:
    build:
      context: ./marketplace_backend
      dockerfile: apps/products/Dockerfile
      target: development
    command: pnpm run start:dev products
    env_file:
      - ./marketplace_backend/apps/products/.env
    ports:
      - '3003:3003'
    volumes:
      - ./marketplace_backend:/app
    depends_on:
      - kafka    
      - db
    networks:
      - my_network

  orders:
    build:
      context: ./marketplace_backend
      dockerfile: apps/orders/Dockerfile
      target: development
    command: pnpm run start:dev orders
    env_file:
      - ./marketplace_backend/apps/orders/.env
    ports:
      - '3004:3004'
    volumes:
      - ./marketplace_backend:/app
    depends_on:
      - kafka    
      - db
    networks:
      - my_network

  inventories:
    build:
      context: ./marketplace_backend
      dockerfile: apps/inventories/Dockerfile
      target: development
    command: pnpm run start:dev inventories
    env_file:
      - ./marketplace_backend/apps/inventories/.env
    ports:
      - '3005:3005'
    volumes:
      - ./marketplace_backend:/app
    depends_on:
      - kafka    
      - db
    networks:
      - my_network


networks:
  my_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  kafka_data:
