services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

  marketplace_backend_gateway:
    build:
      context: ./marketplace_backend
      dockerfile: ./apps/marketplace_backend/Dockerfile
      target: development
    command: pnpm run start:dev marketplace_backend
    env_file:
      - ./apps/marketplace_backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./marketplace_backend:/app
    depends_on:
      - db
  users:
    build:
      context: ./marketplace_backend
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: pnpm run start:dev users
    env_file:
      - ./apps/users/.env
    ports:
      - "3001:3001"
    volumes:
      - ./marketplace_backend:/app
    depends_on:
      - db

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
    driver: local
