services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: muser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace
    env_file:
      - ./marketplace_backend/.env
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

  marketplace_backend_gateway:
    build:
      context: ./marketplace_backend
      dockerfile: apps/marketplace_backend_gateway/Dockerfile
      target: development
    command: pnpm run start:dev marketplace_backend_gateway
    env_file:
      - ./marketplace_backend/apps/marketplace_backend_gateway/.env
    ports:
      - '3000:3000'
    volumes:
      - ./marketplace_backend:/app
    depends_on:
      - db
  auth:
    build:
      context: ./marketplace_backend
      dockerfile: apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./marketplace_backend/apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - ./marketplace_backend:/app
    depends_on:
      - db

  products:
    build:
      context: ./marketplace_backend
      dockerfile: apps/products/Dockerfile
      target: development
    command: pnpm run start:dev products
    env_file:
      - ./marketplace_backend/apps/products/.env
    ports:
      - '3003:3003'
    volumes:
      - ./marketplace_backend:/app
    depends_on:
      - db


networks:
  my_network:
    driver: bridge

volumes:
  db_data:
    driver: local
